// Generated by jextract

package org.webgpu.panama.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUInstanceExtras {
 *     WGPUChainedStruct chain;
 *     WGPUInstanceBackend backends;
 *     WGPUInstanceFlag flags;
 *     WGPUDx12Compiler dx12ShaderCompiler;
 *     WGPUGles3MinorVersion gles3MinorVersion;
 *     WGPUGLFenceBehaviour glFenceBehaviour;
 *     WGPUStringView dxcPath;
 *     WGPUDxcMaxShaderModel dxcMaxShaderModel;
 *     const uint8_t *budgetForDeviceCreation;
 *     const uint8_t *budgetForDeviceLoss;
 * }
 * }
 */
public class WGPUInstanceExtras {

    WGPUInstanceExtras() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        webgpu_h.C_LONG_LONG.withName("backends"),
        webgpu_h.C_LONG_LONG.withName("flags"),
        webgpu_h.C_INT.withName("dx12ShaderCompiler"),
        webgpu_h.C_INT.withName("gles3MinorVersion"),
        webgpu_h.C_INT.withName("glFenceBehaviour"),
        MemoryLayout.paddingLayout(4),
        WGPUStringView.layout().withName("dxcPath"),
        webgpu_h.C_INT.withName("dxcMaxShaderModel"),
        MemoryLayout.paddingLayout(4),
        webgpu_h.C_POINTER.withName("budgetForDeviceCreation"),
        webgpu_h.C_POINTER.withName("budgetForDeviceLoss")
    ).withName("WGPUInstanceExtras");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = $LAYOUT.byteOffset(groupElement("chain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final OfLong backends$LAYOUT = (OfLong)$LAYOUT.select(groupElement("backends"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUInstanceBackend backends
     * }
     */
    public static final OfLong backends$layout() {
        return backends$LAYOUT;
    }

    private static final long backends$OFFSET = $LAYOUT.byteOffset(groupElement("backends"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUInstanceBackend backends
     * }
     */
    public static final long backends$offset() {
        return backends$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUInstanceBackend backends
     * }
     */
    public static long backends(MemorySegment struct) {
        return struct.get(backends$LAYOUT, backends$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUInstanceBackend backends
     * }
     */
    public static void backends(MemorySegment struct, long fieldValue) {
        struct.set(backends$LAYOUT, backends$OFFSET, fieldValue);
    }

    private static final OfLong flags$LAYOUT = (OfLong)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUInstanceFlag flags
     * }
     */
    public static final OfLong flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUInstanceFlag flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUInstanceFlag flags
     * }
     */
    public static long flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUInstanceFlag flags
     * }
     */
    public static void flags(MemorySegment struct, long fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt dx12ShaderCompiler$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dx12ShaderCompiler"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUDx12Compiler dx12ShaderCompiler
     * }
     */
    public static final OfInt dx12ShaderCompiler$layout() {
        return dx12ShaderCompiler$LAYOUT;
    }

    private static final long dx12ShaderCompiler$OFFSET = $LAYOUT.byteOffset(groupElement("dx12ShaderCompiler"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUDx12Compiler dx12ShaderCompiler
     * }
     */
    public static final long dx12ShaderCompiler$offset() {
        return dx12ShaderCompiler$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUDx12Compiler dx12ShaderCompiler
     * }
     */
    public static int dx12ShaderCompiler(MemorySegment struct) {
        return struct.get(dx12ShaderCompiler$LAYOUT, dx12ShaderCompiler$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUDx12Compiler dx12ShaderCompiler
     * }
     */
    public static void dx12ShaderCompiler(MemorySegment struct, int fieldValue) {
        struct.set(dx12ShaderCompiler$LAYOUT, dx12ShaderCompiler$OFFSET, fieldValue);
    }

    private static final OfInt gles3MinorVersion$LAYOUT = (OfInt)$LAYOUT.select(groupElement("gles3MinorVersion"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUGles3MinorVersion gles3MinorVersion
     * }
     */
    public static final OfInt gles3MinorVersion$layout() {
        return gles3MinorVersion$LAYOUT;
    }

    private static final long gles3MinorVersion$OFFSET = $LAYOUT.byteOffset(groupElement("gles3MinorVersion"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUGles3MinorVersion gles3MinorVersion
     * }
     */
    public static final long gles3MinorVersion$offset() {
        return gles3MinorVersion$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUGles3MinorVersion gles3MinorVersion
     * }
     */
    public static int gles3MinorVersion(MemorySegment struct) {
        return struct.get(gles3MinorVersion$LAYOUT, gles3MinorVersion$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUGles3MinorVersion gles3MinorVersion
     * }
     */
    public static void gles3MinorVersion(MemorySegment struct, int fieldValue) {
        struct.set(gles3MinorVersion$LAYOUT, gles3MinorVersion$OFFSET, fieldValue);
    }

    private static final OfInt glFenceBehaviour$LAYOUT = (OfInt)$LAYOUT.select(groupElement("glFenceBehaviour"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUGLFenceBehaviour glFenceBehaviour
     * }
     */
    public static final OfInt glFenceBehaviour$layout() {
        return glFenceBehaviour$LAYOUT;
    }

    private static final long glFenceBehaviour$OFFSET = $LAYOUT.byteOffset(groupElement("glFenceBehaviour"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUGLFenceBehaviour glFenceBehaviour
     * }
     */
    public static final long glFenceBehaviour$offset() {
        return glFenceBehaviour$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUGLFenceBehaviour glFenceBehaviour
     * }
     */
    public static int glFenceBehaviour(MemorySegment struct) {
        return struct.get(glFenceBehaviour$LAYOUT, glFenceBehaviour$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUGLFenceBehaviour glFenceBehaviour
     * }
     */
    public static void glFenceBehaviour(MemorySegment struct, int fieldValue) {
        struct.set(glFenceBehaviour$LAYOUT, glFenceBehaviour$OFFSET, fieldValue);
    }

    private static final GroupLayout dxcPath$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("dxcPath"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUStringView dxcPath
     * }
     */
    public static final GroupLayout dxcPath$layout() {
        return dxcPath$LAYOUT;
    }

    private static final long dxcPath$OFFSET = $LAYOUT.byteOffset(groupElement("dxcPath"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUStringView dxcPath
     * }
     */
    public static final long dxcPath$offset() {
        return dxcPath$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUStringView dxcPath
     * }
     */
    public static MemorySegment dxcPath(MemorySegment struct) {
        return struct.asSlice(dxcPath$OFFSET, dxcPath$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUStringView dxcPath
     * }
     */
    public static void dxcPath(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, dxcPath$OFFSET, dxcPath$LAYOUT.byteSize());
    }

    private static final OfInt dxcMaxShaderModel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dxcMaxShaderModel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUDxcMaxShaderModel dxcMaxShaderModel
     * }
     */
    public static final OfInt dxcMaxShaderModel$layout() {
        return dxcMaxShaderModel$LAYOUT;
    }

    private static final long dxcMaxShaderModel$OFFSET = $LAYOUT.byteOffset(groupElement("dxcMaxShaderModel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUDxcMaxShaderModel dxcMaxShaderModel
     * }
     */
    public static final long dxcMaxShaderModel$offset() {
        return dxcMaxShaderModel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUDxcMaxShaderModel dxcMaxShaderModel
     * }
     */
    public static int dxcMaxShaderModel(MemorySegment struct) {
        return struct.get(dxcMaxShaderModel$LAYOUT, dxcMaxShaderModel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUDxcMaxShaderModel dxcMaxShaderModel
     * }
     */
    public static void dxcMaxShaderModel(MemorySegment struct, int fieldValue) {
        struct.set(dxcMaxShaderModel$LAYOUT, dxcMaxShaderModel$OFFSET, fieldValue);
    }

    private static final AddressLayout budgetForDeviceCreation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("budgetForDeviceCreation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceCreation
     * }
     */
    public static final AddressLayout budgetForDeviceCreation$layout() {
        return budgetForDeviceCreation$LAYOUT;
    }

    private static final long budgetForDeviceCreation$OFFSET = $LAYOUT.byteOffset(groupElement("budgetForDeviceCreation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceCreation
     * }
     */
    public static final long budgetForDeviceCreation$offset() {
        return budgetForDeviceCreation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceCreation
     * }
     */
    public static MemorySegment budgetForDeviceCreation(MemorySegment struct) {
        return struct.get(budgetForDeviceCreation$LAYOUT, budgetForDeviceCreation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceCreation
     * }
     */
    public static void budgetForDeviceCreation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(budgetForDeviceCreation$LAYOUT, budgetForDeviceCreation$OFFSET, fieldValue);
    }

    private static final AddressLayout budgetForDeviceLoss$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("budgetForDeviceLoss"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceLoss
     * }
     */
    public static final AddressLayout budgetForDeviceLoss$layout() {
        return budgetForDeviceLoss$LAYOUT;
    }

    private static final long budgetForDeviceLoss$OFFSET = $LAYOUT.byteOffset(groupElement("budgetForDeviceLoss"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceLoss
     * }
     */
    public static final long budgetForDeviceLoss$offset() {
        return budgetForDeviceLoss$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceLoss
     * }
     */
    public static MemorySegment budgetForDeviceLoss(MemorySegment struct) {
        return struct.get(budgetForDeviceLoss$LAYOUT, budgetForDeviceLoss$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *budgetForDeviceLoss
     * }
     */
    public static void budgetForDeviceLoss(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(budgetForDeviceLoss$LAYOUT, budgetForDeviceLoss$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

